package javagurus.curso.frameworks.model;
// default package
// Generated 1/12/2012 04:06:04 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Cliente generated by hbm2java
 */
public class Cliente implements java.io.Serializable {

	private BigDecimal idcliente;
	private Banco banco;
	private String nombre;
	private String apaterno;
	private String amaterno;
	private BigDecimal edad;
	private Set cuentas = new HashSet(0);

	public Cliente() {
	}

	public Cliente(BigDecimal idcliente, Banco banco, String nombre,
			String apaterno, String amaterno, BigDecimal edad) {
		this.idcliente = idcliente;
		this.banco = banco;
		this.nombre = nombre;
		this.apaterno = apaterno;
		this.amaterno = amaterno;
		this.edad = edad;
	}

	public Cliente(BigDecimal idcliente, Banco banco, String nombre,
			String apaterno, String amaterno, BigDecimal edad, Set cuentas) {
		this.idcliente = idcliente;
		this.banco = banco;
		this.nombre = nombre;
		this.apaterno = apaterno;
		this.amaterno = amaterno;
		this.edad = edad;
		this.cuentas = cuentas;
	}

	public BigDecimal getIdcliente() {
		return this.idcliente;
	}

	public void setIdcliente(BigDecimal idcliente) {
		this.idcliente = idcliente;
	}

	public Banco getBanco() {
		return this.banco;
	}

	public void setBanco(Banco banco) {
		this.banco = banco;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getApaterno() {
		return this.apaterno;
	}

	public void setApaterno(String apaterno) {
		this.apaterno = apaterno;
	}

	public String getAmaterno() {
		return this.amaterno;
	}

	public void setAmaterno(String amaterno) {
		this.amaterno = amaterno;
	}

	public BigDecimal getEdad() {
		return this.edad;
	}

	public void setEdad(BigDecimal edad) {
		this.edad = edad;
	}

	public Set getCuentas() {
		return this.cuentas;
	}

	public void setCuentas(Set cuentas) {
		this.cuentas = cuentas;
	}

}
