package javagurus.curso.frameworks.model;
// default package
// Generated 1/12/2012 04:06:04 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Tipomovimiento generated by hbm2java
 */
public class Tipomovimiento implements java.io.Serializable {

	private BigDecimal idtipomovimiento;
	private String nombre;
	private Set movimientos = new HashSet(0);

	public Tipomovimiento() {
	}

	public Tipomovimiento(BigDecimal idtipomovimiento, String nombre) {
		this.idtipomovimiento = idtipomovimiento;
		this.nombre = nombre;
	}

	public Tipomovimiento(BigDecimal idtipomovimiento, String nombre,
			Set movimientos) {
		this.idtipomovimiento = idtipomovimiento;
		this.nombre = nombre;
		this.movimientos = movimientos;
	}

	public BigDecimal getIdtipomovimiento() {
		return this.idtipomovimiento;
	}

	public void setIdtipomovimiento(BigDecimal idtipomovimiento) {
		this.idtipomovimiento = idtipomovimiento;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Set getMovimientos() {
		return this.movimientos;
	}

	public void setMovimientos(Set movimientos) {
		this.movimientos = movimientos;
	}

}
