package javagurus.curso.frameworks.model;
// default package
// Generated 1/12/2012 04:06:04 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Cuenta generated by hbm2java
 */
public class Cuenta implements java.io.Serializable {

	private BigDecimal idcuenta;
	private Tipocuenta tipocuenta;
	private Cliente cliente;
	private BigDecimal numerocuenta;
	private Set movimientos = new HashSet(0);

	public Cuenta() {
	}

	public Cuenta(BigDecimal idcuenta, Tipocuenta tipocuenta, Cliente cliente,
			BigDecimal numerocuenta) {
		this.idcuenta = idcuenta;
		this.tipocuenta = tipocuenta;
		this.cliente = cliente;
		this.numerocuenta = numerocuenta;
	}

	public Cuenta(BigDecimal idcuenta, Tipocuenta tipocuenta, Cliente cliente,
			BigDecimal numerocuenta, Set movimientos) {
		this.idcuenta = idcuenta;
		this.tipocuenta = tipocuenta;
		this.cliente = cliente;
		this.numerocuenta = numerocuenta;
		this.movimientos = movimientos;
	}

	public BigDecimal getIdcuenta() {
		return this.idcuenta;
	}

	public void setIdcuenta(BigDecimal idcuenta) {
		this.idcuenta = idcuenta;
	}

	public Tipocuenta getTipocuenta() {
		return this.tipocuenta;
	}

	public void setTipocuenta(Tipocuenta tipocuenta) {
		this.tipocuenta = tipocuenta;
	}

	public Cliente getCliente() {
		return this.cliente;
	}

	public void setCliente(Cliente cliente) {
		this.cliente = cliente;
	}

	public BigDecimal getNumerocuenta() {
		return this.numerocuenta;
	}

	public void setNumerocuenta(BigDecimal numerocuenta) {
		this.numerocuenta = numerocuenta;
	}

	public Set getMovimientos() {
		return this.movimientos;
	}

	public void setMovimientos(Set movimientos) {
		this.movimientos = movimientos;
	}

}
